{
 "title": "Account Balance",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up Account",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  name AS metric,\n  value\nFROM accounts\nWHERE\n  $__timeFilter(datetime) AND\n  name = 'Up Account'\nORDER BY datetime\n"
    }
   ]
  },
  {
   "title": "Rent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  value\nFROM accounts\nWHERE\n  name = '🏠 Rent'\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Savings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "prefix: $" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  name AS metric,\n  value\nFROM accounts\nWHERE\n  name = '💰 Savings'\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Total Crypto Holdings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "prefix: US$" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datetime,$__interval),\n  sum(usd) AS \"usd\"\nFROM binanceData\nGROUP BY 1\nORDER BY $__timeGroup(datetime,$__interval)"
    }
   ]
  },
  {
   "title": "Account Balance",
   "type": "graph",
   "description": "Tracks account balance",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  name AS metric,\n  value\nFROM accounts\nWHERE\n  $__timeFilter(datetime) AND\n  name = '💰 Savings'\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  name AS metric,\n  value\nFROM accounts\nWHERE\n  $__timeFilter(datetime) AND\n  name = 'Up Account'\nORDER BY datetime\n"
    },
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  name AS metric,\n  value\nFROM accounts\nWHERE\n  $__timeFilter(datetime) AND\n  name = '🏠 Rent'\nORDER BY datetime\n"
    }
   ]
  },
  {
   "title": "Savings Target",
   "type": "gauge",
   "description": "Required money for a house deposit",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  name AS metric,\n  value\nFROM accounts\nWHERE\n  $__timeFilter(datetime) AND\n  name = '💰 Savings'\nORDER BY datetime\n"
    }
   ]
  },
  {
   "title": "Total Cash",
   "type": "stat",
   "description": "Required money for a house deposit",
   "gridPos": { "h": 6, "w": 2, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "prefix: $" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datetime,$__interval),\n  sum(value) AS \"value\"\nFROM accounts\nGROUP BY 1\nORDER BY $__timeGroup(datetime,$__interval)"
    }
   ]
  },
  {
   "title": "Total Expenses",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "prefix: $" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  value\nFROM transactions\nWHERE\n  $__timeFilter(datetime) AND\n  parentCategory != 'None'\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Total Income",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "prefix: $" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  value\nFROM transactions\nWHERE\n  description = 'Accenture' or \n  description = 'Vinsi' OR\n  description = 'ATO'\nORDER BY datetime"
    }
   ]
  },
  { "title": "Expenses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Weekly Breakdown",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  parentCategory AS metric,\n  abs(value)\nFROM transactions\nWHERE\n  $__timeFilter(datetime) AND\n  parentCategory != 'None'\nORDER BY datetime\n"
    }
   ]
  },
  {
   "title": "Spending Summary",
   "type": "table",
   "description": "Overall spending summary by category",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "prefix: $" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  parentCategory AS metric,\n  value\nFROM transactions\nWHERE\n  parentCategory != 'None'\nORDER BY datetime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "prefix: $" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  value\nFROM transactions\nWHERE\n  $__timeFilter(datetime) AND\n  parentCategory != 'None'\nORDER BY datetime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "prefix: $" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  value\nFROM transactions\nWHERE\n  $__timeFilter(datetime) AND\n  parentCategory != 'None'\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Spending Summary",
   "type": "bargauge",
   "description": "Overall spending summary by category",
   "gridPos": { "h": 16, "w": 9, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "prefix: $" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  subCategory AS metric,\n  abs(value)\nFROM transactions\nWHERE\n  parentCategory != 'None'\nORDER BY datetime"
    }
   ]
  },
  { "title": "Investments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Binance Holdings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  asset AS metric,\n  usd\nFROM binanceData\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Income",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Accenture",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "prefix: $" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  datetime AS \"time\",\n  value\nFROM transactions\nWHERE\n  description = 'Accenture'\nORDER BY datetime"
      }
     ]
    },
    {
     "title": "Vinsi",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "prefix: $" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  datetime AS \"time\",\n  value\nFROM transactions\nWHERE\n  description = 'Vinsi'\nORDER BY datetime"
      }
     ]
    },
    {
     "title": "Income",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "prefix: $" } },
     "targets": [
      {
       "rawSql": "SELECT\n  datetime AS \"time\",\n  value, description\nFROM transactions\nWHERE\n  parentCategory = 'None' AND\n  description = 'Vinsi' OR\n  description = 'Accenture' OR\n  description = 'ATO'\n  \nORDER BY datetime"
      }
     ]
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transactions",
     "type": "table",
     "gridPos": { "h": 11, "w": 9, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "rawSql": "SELECT\n  datetime AS \"time\",\n  value,\n  subCategory,\n  description\nFROM transactions\nWHERE\n  $__timeFilter(datetime) AND\n  parentCategory != 'None'\nORDER BY datetime"
      }
     ]
    },
    {
     "title": "Transactions: Last 7 Days",
     "type": "table",
     "gridPos": { "h": 18, "w": 9, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "rawSql": "SELECT\n  datetime AS \"time\",\n  value,\n  subCategory,\n  description\nFROM transactions\nWHERE\n  $__timeFilter(datetime) AND\n  parentCategory != 'None'\nORDER BY datetime"
      }
     ]
    }
   ]
  }
 ]
}